### ISSUE TITLE
the certificate of the web socket has expired

### ISSUE THREAD

**Issue by dick10** [aisstream/example#18]
I'm starting up my project again after some months of other priorities. But now I notice that the certificate of the web socket has expired, thus no connection is established.

      throw er; // Unhandled 'error' event
      ^
Error: certificate has expired
    at TLSSocket.onConnectSecure (node:_tls_wrap:1600:34)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket._finishInit (node:_tls_wrap:1017:8)
    at ssl.onhandshakedone (node:_tls_wrap:803:12)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/usr/src/node_modules/ws/lib/websocket.js:1016:13)
    at ClientRequest.<anonymous> (/usr/src/node_modules/ws/lib/websocket.js:864:5)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'CERT_HAS_EXPIRED'
}

**Comment by hosain-cse2** [comment]
Did u get any solution?
I have the same issue. It was working last night when i finished working.
When I run it again this morning I also got a similar error while connecting to the web socket.

Error: certificate has expired
    at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)
    at TLSSocket.emit (node:events:524:28)     
    at TLSSocket._finishInit (node:_tls_wrap:1076:8)
    at ssl.onhandshakedone (node:_tls_wrap:862:12) {
  code: 'CERT_HAS_EXPIRED'
}

Is this already known?
Is some one working on this?

**Comment by vs-postmedia** [comment]
Same, websocket returning this error: certificate has expired

Appears to have started around 4am (Pacific) for me

**Comment by dickvanhemert** [comment]
Two years ago the issue was resolved by aisstream renewing a certificate. Took about a day for them to notice if i remember correctly. Hopefully it will be the same this time for you Guys.

**Comment by vs-postmedia** [comment]
@hosain-cse2 I disabled SSL checks on my stream for now & it's working. tmp fix until the cert is (hopefully) renewed
